
//
// Jolt-physics
#include <third.party/jolt-physics/Jolt/AABBTree/AABBTreeBuilder.cpp>
#include <third.party/jolt-physics/Jolt/Compute/CPU/ComputeBufferCPU.cpp>
#include <third.party/jolt-physics/Jolt/Compute/CPU/ComputeQueueCPU.cpp>
#include <third.party/jolt-physics/Jolt/Compute/CPU/ComputeSystemCPU.cpp>
#include <third.party/jolt-physics/Jolt/Compute/ComputeSystem.cpp>
#include <third.party/jolt-physics/Jolt/Compute/DX12/ComputeBufferDX12.cpp>
#include <third.party/jolt-physics/Jolt/Compute/DX12/ComputeQueueDX12.cpp>
#include <third.party/jolt-physics/Jolt/Compute/DX12/ComputeSystemDX12.cpp>
#include <third.party/jolt-physics/Jolt/Compute/DX12/ComputeSystemDX12Impl.cpp>
#include <third.party/jolt-physics/Jolt/Compute/VK/ComputeBufferVK.cpp>
#include <third.party/jolt-physics/Jolt/Compute/VK/ComputeQueueVK.cpp>
#include <third.party/jolt-physics/Jolt/Compute/VK/ComputeShaderVK.cpp>
#include <third.party/jolt-physics/Jolt/Compute/VK/ComputeSystemVK.cpp>
#include <third.party/jolt-physics/Jolt/Compute/VK/ComputeSystemVKImpl.cpp>
#include <third.party/jolt-physics/Jolt/Compute/VK/ComputeSystemVKWithAllocator.cpp>
#include <third.party/jolt-physics/Jolt/Core/Color.cpp>
#include <third.party/jolt-physics/Jolt/Core/Factory.cpp>
#include <third.party/jolt-physics/Jolt/Core/IssueReporting.cpp>
#include <third.party/jolt-physics/Jolt/Core/JobSystemSingleThreaded.cpp>
#include <third.party/jolt-physics/Jolt/Core/JobSystemThreadPool.cpp>
#include <third.party/jolt-physics/Jolt/Core/JobSystemWithBarrier.cpp>
#include <third.party/jolt-physics/Jolt/Core/LinearCurve.cpp>
#include <third.party/jolt-physics/Jolt/Core/Memory.cpp>
#include <third.party/jolt-physics/Jolt/Core/Profiler.cpp>
#include <third.party/jolt-physics/Jolt/Core/RTTI.cpp>
#include <third.party/jolt-physics/Jolt/Core/Semaphore.cpp>
#include <third.party/jolt-physics/Jolt/Core/StringTools.cpp>
#include <third.party/jolt-physics/Jolt/Core/TickCounter.cpp>
#include <third.party/jolt-physics/Jolt/Geometry/ConvexHullBuilder.cpp>
#include <third.party/jolt-physics/Jolt/Geometry/ConvexHullBuilder2D.cpp>
#include <third.party/jolt-physics/Jolt/Geometry/Indexify.cpp>
#include <third.party/jolt-physics/Jolt/Geometry/OrientedBox.cpp>
#include <third.party/jolt-physics/Jolt/Math/Vec3.cpp>
#include <third.party/jolt-physics/Jolt/ObjectStream/ObjectStream.cpp>
#include <third.party/jolt-physics/Jolt/ObjectStream/ObjectStreamBinaryIn.cpp>
#include <third.party/jolt-physics/Jolt/ObjectStream/ObjectStreamBinaryOut.cpp>
#include <third.party/jolt-physics/Jolt/ObjectStream/ObjectStreamIn.cpp>
#include <third.party/jolt-physics/Jolt/ObjectStream/ObjectStreamOut.cpp>
#include <third.party/jolt-physics/Jolt/ObjectStream/ObjectStreamTextIn.cpp>
#include <third.party/jolt-physics/Jolt/ObjectStream/ObjectStreamTextOut.cpp>
#include <third.party/jolt-physics/Jolt/ObjectStream/SerializableObject.cpp>
#include <third.party/jolt-physics/Jolt/ObjectStream/TypeDeclarations.cpp>
#include <third.party/jolt-physics/Jolt/Physics/Body/Body.cpp>
#include <third.party/jolt-physics/Jolt/Physics/Body/BodyCreationSettings.cpp>
#include <third.party/jolt-physics/Jolt/Physics/Body/BodyInterface.cpp>
#include <third.party/jolt-physics/Jolt/Physics/Body/BodyManager.cpp>
#include <third.party/jolt-physics/Jolt/Physics/Body/MassProperties.cpp>
#include <third.party/jolt-physics/Jolt/Physics/Body/MotionProperties.cpp>
#include <third.party/jolt-physics/Jolt/Physics/Character/Character.cpp>
#include <third.party/jolt-physics/Jolt/Physics/Character/CharacterBase.cpp>
#include <third.party/jolt-physics/Jolt/Physics/Character/CharacterVirtual.cpp>
#include <third.party/jolt-physics/Jolt/Physics/Collision/BroadPhase/BroadPhase.cpp>
#include <third.party/jolt-physics/Jolt/Physics/Collision/BroadPhase/BroadPhaseBruteForce.cpp>
#include <third.party/jolt-physics/Jolt/Physics/Collision/BroadPhase/BroadPhaseQuadTree.cpp>
#include <third.party/jolt-physics/Jolt/Physics/Collision/BroadPhase/QuadTree.cpp>
#include <third.party/jolt-physics/Jolt/Physics/Collision/CastConvexVsTriangles.cpp>
#include <third.party/jolt-physics/Jolt/Physics/Collision/CastSphereVsTriangles.cpp>
#include <third.party/jolt-physics/Jolt/Physics/Collision/CollideConvexVsTriangles.cpp>
#include <third.party/jolt-physics/Jolt/Physics/Collision/CollideSphereVsTriangles.cpp>
#include <third.party/jolt-physics/Jolt/Physics/Collision/CollisionDispatch.cpp>
#include <third.party/jolt-physics/Jolt/Physics/Collision/CollisionGroup.cpp>
#include <third.party/jolt-physics/Jolt/Physics/Collision/EstimateCollisionResponse.cpp>
#include <third.party/jolt-physics/Jolt/Physics/Collision/GroupFilter.cpp>
#include <third.party/jolt-physics/Jolt/Physics/Collision/GroupFilterTable.cpp>
#include <third.party/jolt-physics/Jolt/Physics/Collision/ManifoldBetweenTwoFaces.cpp>
#include <third.party/jolt-physics/Jolt/Physics/Collision/NarrowPhaseQuery.cpp>
#include <third.party/jolt-physics/Jolt/Physics/Collision/NarrowPhaseStats.cpp>
#include <third.party/jolt-physics/Jolt/Physics/Collision/PhysicsMaterial.cpp>
#include <third.party/jolt-physics/Jolt/Physics/Collision/PhysicsMaterialSimple.cpp>
#include <third.party/jolt-physics/Jolt/Physics/Collision/Shape/BoxShape.cpp>
#include <third.party/jolt-physics/Jolt/Physics/Collision/Shape/CapsuleShape.cpp>
#include <third.party/jolt-physics/Jolt/Physics/Collision/Shape/CompoundShape.cpp>
#include <third.party/jolt-physics/Jolt/Physics/Collision/Shape/ConvexHullShape.cpp>
#include <third.party/jolt-physics/Jolt/Physics/Collision/Shape/ConvexShape.cpp>
#include <third.party/jolt-physics/Jolt/Physics/Collision/Shape/CylinderShape.cpp>
#include <third.party/jolt-physics/Jolt/Physics/Collision/Shape/DecoratedShape.cpp>
#include <third.party/jolt-physics/Jolt/Physics/Collision/Shape/EmptyShape.cpp>
#include <third.party/jolt-physics/Jolt/Physics/Collision/Shape/HeightFieldShape.cpp>
#include <third.party/jolt-physics/Jolt/Physics/Collision/Shape/MeshShape.cpp>
#include <third.party/jolt-physics/Jolt/Physics/Collision/Shape/MutableCompoundShape.cpp>
#include <third.party/jolt-physics/Jolt/Physics/Collision/Shape/OffsetCenterOfMassShape.cpp>
#include <third.party/jolt-physics/Jolt/Physics/Collision/Shape/PlaneShape.cpp>
#include <third.party/jolt-physics/Jolt/Physics/Collision/Shape/RotatedTranslatedShape.cpp>
#include <third.party/jolt-physics/Jolt/Physics/Collision/Shape/ScaledShape.cpp>
#include <third.party/jolt-physics/Jolt/Physics/Collision/Shape/Shape.cpp>
#include <third.party/jolt-physics/Jolt/Physics/Collision/Shape/SphereShape.cpp>
#include <third.party/jolt-physics/Jolt/Physics/Collision/Shape/StaticCompoundShape.cpp>
#include <third.party/jolt-physics/Jolt/Physics/Collision/Shape/TaperedCapsuleShape.cpp>
#include <third.party/jolt-physics/Jolt/Physics/Collision/Shape/TaperedCylinderShape.cpp>
#include <third.party/jolt-physics/Jolt/Physics/Collision/Shape/TriangleShape.cpp>
#include <third.party/jolt-physics/Jolt/Physics/Collision/TransformedShape.cpp>
