font_list = ( 
  {
    path = "B612/B612-Regular.ttf";
    sizes = ( 32, 48, 64 );
    glyph_ranges = ( ( 32, 255 ) );
  }, 
  {
    path = "B612/B612-Bold.ttf";
    sizes = ( 32, 48, 64 );
    glyph_ranges = ( ( 32, 255 ) );
  }, 
  {
    path = "nerd-fonts/TerminessNerdFontMono-Regular.ttf";
    sizes = ( 24 );
    glyph_ranges = ( ( 32, 255 ), ( 57504, 57507 ), ( 57520, 57556 ), ( 61440, 61618 ), ( 61632, 62176 ), ( 57856, 58025 ) );
  }, 
  {
    path = "nerd-fonts/ZedMonoNerdFontMono-Medium.ttf";
    sizes = ( 24 );
    glyph_ranges = ( ( 32, 255 ), ( 57504, 57507 ), ( 57520, 57556 ), ( 61440, 61618 ), ( 61632, 62176 ), ( 57856, 58025 ) );
  }, 
  {
    path = "nerd-fonts/GeistMonoNerdFontMono-Medium.ttf";
    sizes = ( 24 );
    glyph_ranges = ( ( 32, 255 ), ( 57504, 57507 ), ( 57520, 57556 ), ( 61440, 61618 ), ( 61632, 62176 ), ( 57856, 58025 ) );
  } );
