font_list = ( 
  {
    path = "B612/B612-Regular.ttf";
    sizes = ( 32, 48, 64 );
    glyph_ranges = ( ( 32, 255 ) );
  }, 
  {
    path = "B612/B612-Bold.ttf";
    sizes = ( 32, 48, 64 );
    glyph_ranges = ( ( 32, 255 ) );
  }, 
  {
    path = "nerd-fonts/TerminessNerdFontMono-Regular.ttf";
    sizes = ( 24 );
    glyph_ranges = ( ( 32, 255 ), ( 57504, 57507 ), ( 57520, 57556 ), ( 61440, 61618 ), ( 61632, 62176 ), ( 57856, 58025 ) );
  }, 
  {
    path = "nerd-fonts/ZedMonoNerdFontMono-Medium.ttf";
    sizes = ( 24 );
    glyph_ranges = ( ( 32, 255 ), ( 57504, 57507 ), ( 57520, 57556 ), ( 61440, 61618 ), ( 61632, 62176 ), ( 57856, 58025 ) );
  }, 
  {
    path = "nerd-fonts/GeistMonoNerdFontMono-Medium.ttf";
    sizes = ( 24 );
    glyph_ranges = ( ( 32, 255 ), ( 57504, 57507 ), ( 57520, 57556 ), ( 61440, 61618 ), ( 61632, 62176 ), ( 57856, 58025 ) );
  } );

  compass: {
    xmargin = 256.0;
    ymargin = 0.0;
    angle_increment = 15.0;
    label_angle_multiple = 30.0;
    arc_degrees = 120.0;
    glyph_major = "|";
    glyph_minor = "+";
  };

  # altimeter: {
  #   xmargin = 256.0;
  #   ymargin = 256.0;
  #   range = 300.0;
  #   increment = 10.0;
  #   bar_ends_len = 32.0;
  #   bar_width = 8.0;
  #   marker_big_meters = 50.0;
  #   marker_big_len = 16.0;
  #   marker_small_len = 8.0;
  #   marker_height = 4.0;
  # };
  altimeter: {
    xmargin = -256.0;
    ymargin = 256.0;
    range = 300.0;
    increment = 10.0;
    bar_ends_len = 32.0;
    bar_width = 8.0;
    marker_big_meters = 50.0;
    marker_big_len = 16.0;
    marker_small_len = 8.0;
    marker_height = 4.0;
    dir_x = 0.0;
    dir_y = 1.0;
    marker_dir_x = -1.0;
    marker_dir_y = 0.0;
  };

  speedometer: {
    xmargin = 256.0;
    ymargin = 256.0;
    range = 300.0;
    increment = 10.0;
    bar_ends_len = 32.0;
    bar_width = 8.0;
    marker_big_meters = 50.0;
    marker_big_len = 16.0;
    marker_small_len = 8.0;
    marker_height = 4.0;
    dir_x =0.0;
    dir_y =1.0;
    marker_dir_x =-1.0;
    marker_dir_y =0.0;
  };

