#include <cstdio>
#include <cstdlib>
#include <cstdint>
#include <string>
#include <cassert>
#include <system_error>
#include <vector>
#include <algorithm>
#include <ranges>
#include <unordered_map>
#include <ostream>
#include <sstream>
#include <chrono>

#include <fmt/format.h>
#include <fmt/std.h>
#include <fmt/chrono.h>
#include <rfl.hpp>
#include <rfl/json.hpp>
#include <filesystem>
#include <ktx.h>
#include <Lz/Lz.hpp>
#include <vulkan/vulkan_core.h>
#include <stb/stb_image.h>
#include <mio/mmap.hpp>
#include <lyra/lyra.hpp>

#include <xray/rendering/sprite.system/sprite.defs.hpp>
#include <xray/base/fnv_hash.hpp>
#include <xray/base/serialization/rfl.libconfig/config.save.hpp>
#include <xray/math/serialization/parser.scalar2.hpp>

struct TpSheet_Size
{
    uint32_t w;
    uint32_t h;
};

struct TpSheet_Rect
{
    uint32_t x;
    uint32_t y;
    uint32_t w;
    uint32_t h;
};

struct TpSheet_SpriteDef
{
    std::string filename;
    TpSheet_Rect frame;
    TpSheet_Rect spriteSourceSize;
    TpSheet_Size sourceSize;
    bool rotated;
    bool trimmed;
};

struct TpSheet_Meta
{
    std::string app;
    std::string version;
    std::string format;
    std::string image;
    TpSheet_Size size;
    std::string scale;
    std::string smartupdate;
};

struct TpSheet_Texture
{
    std::string image;
    TpSheet_Size size;
    std::vector<TpSheet_SpriteDef> sprites;
};

struct TpSheet_Def
{
    std::vector<TpSheet_SpriteDef> frames;
    TpSheet_Meta meta;
};

struct TpSheet_Vec2
{
    float x;
    float y;
};

struct TpSheet_AtlasEntry
{
    uint32_t layer;
    uint32_t x;
    uint32_t y;
    uint32_t width;
    uint32_t height;
    uint64_t hashed_name;
    TpSheet_Vec2 bottom_left;
    TpSheet_Vec2 top_left;
    TpSheet_Vec2 top_right;
    TpSheet_Vec2 bottom_right;
};

struct TpSheet_AtlasDef
{
    // TODO: bug in the libconfig writer with unordered_map, need to fix it later
    // std::unordered_map<uint64_t, xray::rendering::TextureRegion> frames;
    std::vector<TpSheet_AtlasEntry> frames;
    std::filesystem::path texture_file;
};

namespace fs = std::filesystem;

constexpr const char* const HPP_TEMPLATE = R"#(
#pragma once

#include <cstdint>
#include "xray/rendering/sprite.system/sprite.defs.hpp"

//
// automatically generated by atlas tool @ {date_time_gen}

namespace {ns_template} {{

struct SpriteIds {{
    {sprite_ids_list}
}};

}} // namespace {ns_template}
)#";

int
main(int argc, char** argv)
{
    fs::path input_dir_path;
    fs::path output_dir_path;
    std::string atlas_texture_prefix;
    std::string atlas_name;
    std::string hpp_file;
    bool show_help{ false };

    constexpr const std::string_view usage_example = R"#(
Texture atlas creation tool.
Example usage:
    $ atlas-tool -i ~/projects/misc/packed.textures/crosshairs -o ~/projects/xray-assets/assets/textures/hud -p "hud" crosshairs
    )#";

    auto cli = lyra::help{ show_help }.description(usage_example.data()) |
               lyra::opt{ input_dir_path, "directory" }["-i"]["--input-dir"]("Input directory with the sprite sheets")
                   .required() |
               lyra::opt{ output_dir_path, "directory" }["-o"]["--out-dir"](
                   "Output directory with the atlas definition and KTX2 texture files")
                   .required() |
               lyra::opt{ atlas_texture_prefix, "prefix" }["-p"]["--prefix"]("Atlas texture file prefix").required() |
               lyra::arg{ atlas_name, "name" }("Atlas name").required() |
               lyra::opt{ hpp_file, "header file" }["-H"]["--hpp"]("Header file name");

    auto arg_parse_result = cli.parse({ argc, argv });
    if (!arg_parse_result) {
        fmt::println("Error: {}", arg_parse_result.message());
    }

    if (show_help || !arg_parse_result) {
        std::ostringstream ostr;
        ostr << cli;
        fmt::println("{}", ostr.str());
        return EXIT_FAILURE;
    }

    std::vector<TpSheet_Def> atlas_defs;
    for (const fs::directory_entry& dir_entry : fs::recursive_directory_iterator{ input_dir_path }) {
        if (dir_entry.is_regular_file() && dir_entry.path().extension() == ".json") {
            rfl::Result<TpSheet_Def> atlas_result = rfl::json::load<TpSheet_Def>(dir_entry.path().generic_string());
            if (!atlas_result) {
                fmt::println("Failed to load atlas {}, error {}", dir_entry.path(), atlas_result.error().what());
                return EXIT_FAILURE;
            }

            if (atlas_result->frames.empty()) {
                fmt::println("Warning: atlas {} has no frames, ignoring ...", dir_entry.path());
                continue;
            }

            atlas_defs.push_back(std::move(atlas_result.value()));
        }
    }

    //
    // textures should be max 2048x2048
    const bool texture_size_check_fails = std::ranges::any_of(
        atlas_defs, [](const TpSheet_Def& sheet) { return sheet.meta.size.w > 2048 || sheet.meta.size.h > 2048; });

    if (texture_size_check_fails) {
        fmt::println("Textures should have a max of 2048 pixels");
        return EXIT_FAILURE;
    }

    ktxTextureCreateInfo tex_create_info{
        .vkFormat = VK_FORMAT_R8_UNORM,
        .pDfd = nullptr,
        .baseWidth = 2048,
        .baseHeight = 2048,
        .baseDepth = 1,
        .numDimensions = 2,
        .numLevels = 1,
        .numLayers = static_cast<uint32_t>(atlas_defs.size()),
        .numFaces = 1,
        .isArray = true,
        .generateMipmaps = false,
    };

    ktxTexture2* atlas_tex{ nullptr };
    if (const ktx_error_code_e e = ktxTexture2_Create(&tex_create_info, KTX_TEXTURE_CREATE_ALLOC_STORAGE, &atlas_tex);
        e != ktx_error_code_e::KTX_SUCCESS) {
        fmt::println("Failed to create KTX2 texture, error {}", fmt::underlying(e));
        return EXIT_FAILURE;
    }

    TpSheet_AtlasDef atlas_definition{
        .frames = {},
        .texture_file = fmt::format("{}/{}.ktx2", atlas_texture_prefix, atlas_name),
    };

    std::string sprite_ids{};
    sprite_ids.reserve(2048);

    for (const auto& [sheet_index, sheet] : lz::enumerate(atlas_defs)) {
        const fs::path image_path = input_dir_path / sheet.meta.image;
        fmt::println("image: {} -> {}x{}", image_path, sheet.meta.size.w, sheet.meta.size.h);

        const float SHEET_WIDTH = static_cast<float>(sheet.meta.size.w);
        const float SHEET_HEIGHT = static_cast<float>(sheet.meta.size.h);

        //
        // insert frames
        for (auto&& [layer_index, tex] : lz::enumerate(sheet.frames)) {
            const uint64_t hashed_name = FNV::fnv1a(tex.filename);
            fmt::println("sprite {} -> {}", tex.filename, hashed_name);

            auto make_cpp_conformat_name = [](const std::string_view& sv) {
                return lz::chain(sv)
                    .map([](char c) {
                        if (isspace(c) || !isalnum(c) || c == '.')
                            return '_';

                        return static_cast<char>(toupper(c));
                    })
                    .toString();
            };

            const TpSheet_AtlasEntry se{
                .layer = 0,
                .x = tex.frame.x,
                .y = tex.frame.y,
                .width = tex.frame.w,
                .height = tex.frame.h,
                .hashed_name = hashed_name,
                .bottom_left =
                    TpSheet_Vec2{
                        .x = static_cast<float>(tex.frame.x) / SHEET_WIDTH,
                        .y = static_cast<float>(tex.frame.y + tex.frame.h) / SHEET_HEIGHT,
                    },
                .top_left =
                    TpSheet_Vec2{
                        .x = static_cast<float>(tex.frame.x) / SHEET_WIDTH,
                        .y = static_cast<float>(tex.frame.y) / SHEET_HEIGHT,
                    },
                .top_right =
                    TpSheet_Vec2{
                        .x = static_cast<float>(tex.frame.x + tex.frame.w) / SHEET_WIDTH,
                        .y = static_cast<float>(tex.frame.y) / SHEET_HEIGHT,
                    },
                .bottom_right =
                    TpSheet_Vec2{
                        .x = static_cast<float>(tex.frame.x + tex.frame.w) / SHEET_WIDTH,
                        .y = static_cast<float>(tex.frame.y + tex.frame.h) / SHEET_HEIGHT,
                    },
            };

            fmt::format_to(std::back_inserter(sprite_ids),
                           // "static constexpr const  {0} {{ {1} }};\n",
                           R"#(
    static constexpr const xray::rendering::SpriteEntry {sprite_name} {{
        .Handle = xray::rendering::SpriteHandleType{{ {sprite_handle} }},
        .U16Size = {{ .width = {sprite_width}, .height = {sprite_height} }},
        .F32Size = {{ .width = {f32_width}.0f, .height = {f32_height}.0f }},
        .Texture = {{
            .layer = {layer},
            .bottom_left = {{ {blx}, {bly} }},
            .top_left = {{ {tlx}, {tly} }},
            .top_right = {{ {trx}, {try} }},
            .bottom_right = {{ {brx}, {bry} }},
        }},
    }};)#",
                           fmt::arg("sprite_name", make_cpp_conformat_name(tex.filename)),
                           fmt::arg("sprite_handle", hashed_name),
                           fmt::arg("sprite_width", tex.sourceSize.w),
                           fmt::arg("sprite_height", tex.sourceSize.h),
                           fmt::arg("f32_width", static_cast<float>(tex.sourceSize.w)),
                           fmt::arg("f32_height", static_cast<float>(tex.sourceSize.h)),
                           fmt::arg("layer", sheet_index),
                           fmt::arg("blx", se.bottom_left.x),
                           fmt::arg("bly", se.bottom_left.y),
                           fmt::arg("tlx", se.top_left.x),
                           fmt::arg("tly", se.top_left.y),
                           fmt::arg("trx", se.top_right.x),
                           fmt::arg("try", se.top_right.y),
                           fmt::arg("brx", se.bottom_right.x),
                           fmt::arg("bry", se.bottom_right.y));

            // auto [itr, was_inseted] = atlas_definition.frames.emplace(hashed_name,
            //                                                           xray::rendering::TextureRegion{
            //                                                               .layer =
            //                                                               static_cast<uint32_t>(layer_index), .x =
            //                                                               sprite.region.x, .y = sprite.region.y,
            //                                                               .width = sprite.region.w,
            //                                                               .height = sprite.region.h,
            //                                                           });

            atlas_definition.frames.emplace_back(se);

            // if (!was_inseted) {
            //     fmt::println("WARNING: sprite {} name collision!", sprite.filename);
            // }
            // }
        }

        //
        // copy data to texture
        {
            std::error_code e{};
            mio::mmap_source mmaped_file = mio::make_mmap_source(image_path.string(), e);
            if (e) {
                fmt::println("Failed to load image {}, error {}", image_path, e.message());
                return EXIT_FAILURE;
            }

            int32_t width{};
            int32_t height{};
            int32_t channels{};

            const stbi_uc* pixels = stbi_load_from_memory(reinterpret_cast<const stbi_uc*>(mmaped_file.data()),
                                                          static_cast<int32_t>(mmaped_file.size()),
                                                          &width,
                                                          &height,
                                                          &channels,
                                                          1);
            if (!pixels) {
                fmt::println("Failed to load data for image {}", image_path);
                return EXIT_FAILURE;
            }

            const ktx_error_code_e e_img = ktxTexture_SetImageFromMemory(ktxTexture(atlas_tex),
                                                                         0,
                                                                         static_cast<ktx_uint32_t>(0),
                                                                         0,
                                                                         pixels,
                                                                         static_cast<ktx_size_t>(width * height));
            if (e_img != ktx_error_code_e::KTX_SUCCESS) {
                fmt::println("KTX error while copying pixels to texture: {}", fmt::underlying(e_img));
                return EXIT_FAILURE;
            }
        }
    }

    const fs::path texture_path = (output_dir_path / atlas_name).concat(".ktx2");
    if (const ktx_error_code_e e =
            ktxTexture_WriteToNamedFile(ktxTexture(atlas_tex), texture_path.generic_string().c_str());
        e != ktx_error_code_e::KTX_SUCCESS) {
        fmt::println("Failed to write KTX2 file {}, error {}", texture_path, fmt::underlying(e));
        return EXIT_FAILURE;
    }

    const fs::path config_file_path = (output_dir_path / atlas_name).concat(".conf");
    if (const rfl::Result<rfl::Nothing> res = rfl::libconfig::save(config_file_path.generic_string(), atlas_definition);
        !res) {
        fmt::println("Failed to write atlas {} definition ({})", config_file_path, res.error().what());
        return EXIT_FAILURE;
    }

    const std::chrono::zoned_time current_time{
        std::chrono::current_zone(),
        std::chrono::system_clock::now(),
    };
    std::ostringstream date_time_gen;
    date_time_gen << current_time;

    const std::string file_content = fmt::format(HPP_TEMPLATE,
                                                 fmt::arg("ns_template", "B5"),
                                                 fmt::arg("date_time_gen", date_time_gen.str()),
                                                 fmt::arg("sprite_ids_list", sprite_ids));

    const fs::path hpp_file_path = (output_dir_path / (hpp_file.empty() ? atlas_name : hpp_file)).concat(".hpp");
    FILE* hpp = fopen(hpp_file_path.generic_string().c_str(), "wt");
    if (!hpp) {
        fmt::println("Failed to write HPP file {}", hpp_file_path.generic_string());
        return EXIT_FAILURE;
    }

    fputs(file_content.c_str(), hpp);

    fmt::println("Wrote atlas: {}, {},\nHPP file {}", texture_path, config_file_path, file_content);
    return EXIT_SUCCESS;
}
